# Generated by Django 3.0.8 on 2022-02-10 20:02

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=50, unique=True)),
                ('wiki', ckeditor_uploader.fields.RichTextUploadingField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user_team', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=50, null=True)),
                ('tags', models.CharField(choices=[('logical', 'logical'), ('functional', 'functional'), ('performance', 'performance'), ('security', 'security'), ('bug', 'bug'), ('frontend', 'frontend'), ('guideline', 'guideline'), ('naming', 'naming')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('to be discussed ', 'to be discussed '), ('resolved', 'resolved'), ('in review', 'in review')], max_length=50, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('composer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_user', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='issues.Projects')),
            ],
        ),
    ]
